spring:
  application:
    name: update-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

server:
    port: 8080

logging:
  level:
    root: debug
