spring:
  application:
    name: update-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

server:
    port: 8080
    tomcat:
      max-swallow-size: 500MB
      connection-timeout: 60000

logging:
  level:
    root: debug
